# Generated by Django 2.1.7 on 2019-05-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('year', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('courses', models.CharField(max_length=200)),
                ('strength', models.IntegerField()),
                ('admission', models.DateField()),
            ],
        ),
    ]
